### ISSUE TITLE
Feature request: flex gap fallback

### ISSUE THREAD

**Issue by gorkamolero** [AndreasFaust/react-raster#19]
Hey!

Thanks a lot for the guide. It's perfect. Moving everything over.

I'd like to request a feature if you have time. We can provide gridRowGap but when doing gap for flex boxes, Safari would complain.

There's this library called react-styled-flex that handles it perfectly. Perhaps it would be a good addition?

All the best

**Comment by AndreasFaust** [comment]
I’m glad, that the migration guide helped. 
Version 7 already had a gap-feature for flexbox, but I removed it for version 8, because it made things much more complicated and the effect can be achived in other ways. Also in about a year, when flex-gap is fully browser-supported, the problem is solved once and for all. 

**Please note:** Update to version 8.1.1, because I optimized performance a lot. Also it supports the short-versions `gap`, `gridGap`, `flexGap`, etc.

If the library is useful to you, please consider supporting it by giving it a star.
